### ISSUE TITLE
SCM example is missing data files

### ISSUE THREAD

**Issue by mcgibbon** [CliMT/climt-future#5]
When running radiative_equilibrium_rrtmg.py in examples, I get this traceback:

```
Traceback (most recent call last):
  File "radiative_equilibrium_rrtmg.py", line 32, in <module>
    tp_profiles = np.loadtxt('tp_profiles').transpose()
  File "/home/disk/eos4/mcgibbon/anaconda/lib/python2.7/site-packages/numpy/lib/npyio.py", line 858, in loadtxt
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: 'tp_profiles'
```

It seems the data files for this example are missing from the repo. This could be fixed alongside #2.

**Comment by JoyMonteiro** [comment]
Fixed.
